name: rux
description: my custom image
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - ryanabx/cosmic

  - type: rpm-ostree
    install:
      - cosmic-desktop
      - cosmic-term
      - cosmic-files
      - cosmic-edit

  - type: systemd
    system:
      enabled:
        - cosmic-greeter.service
      disabled:
        - sddm.service
        - gdm.service

  - type: signing