name: rux
description: my custom image
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest

modules:
  - type: dnf
    group-install:
      with-optional: true
      packages:
        - cosmic-desktop
        - cosmic-desktop-apps

  - type: signing